### ISSUE TITLE
`seggpt.check_dependencies` permanently changes working directory

### ISSUE THREAD

**Issue by ethanmusser** [autodistill/autodistill-seggpt#1]
This line in `seggpt.check_dependencies` changes the working directory of the Python process, but never reverts to the original working directory once the dependency check is complete.  This lack of revert causes paths to be incorrectly resolved in programs that import `seggpt`.

https://github.com/autodistill/autodistill-seggpt/blob/ad60a7a221ec68ddfed43df2fbf06408767c4fd8/autodistill_seggpt/seggpt.py#L16

**Comment by andrew-healey** [comment]
You're right, thanks for reporting this! This issue is now fixed.
